### ISSUE TITLE
Timon name and icon is the same at the actual App name and Icon

### ISSUE THREAD

**Issue by sharlotlek** [Erithano/Timon-Your-FAQ-bot-for-Microsoft-Teams#4]
The name and icon of the Bot is the same as the actuall app name and Icon, I tried to do a teams cache but nothing is still the same

**Comment by Erithano** [comment]
Hey @sharlotlek! 

Yes, the bot name and icon in Power Virtual Agents and in the Teams manifest (Teams app) are the same if you follow the guide.
(You can change the name and icon to whatever you want).

Could you please explain more about what your issue is?

Have an awesome day,
/E

**Comment by sharlotlek** [comment]
Hi @Erithano, Thank you for the quick response

Yes, I changed the Bot name and Icon on PVA but Its not getting the Bot name and icon but rather the Teams app name. please see the below example. 
The actual name of the bot is **Timon** and it has its own icon but in my case its getting the name and icon of the Teams app which is called the **AdoptionHub**. I know how to change the bot name and icon on PVA and the teams app on the menifest file.

![Image example](https://user-images.githubusercontent.com/42436712/163032656-48aa3931-9eaa-47d5-9be9-34db7fa6ed02.jpg)

**Comment by Erithano** [comment]
### Thanks for clarifying this @sharlotlek! 

I like the dark mode by the way 🙂

Didn't know if you were using Timon standalone or within Adoption Hub.

If standalone of course bot name and icon are the same. 
But when used within another app (like Adoption Hub) it inherits that application's name and icon.

You're talking to Timon in the chat tab within AdoptionHub, right?
![image](https://user-images.githubusercontent.com/65014935/163177985-5c0b98ce-29b8-420d-a147-012cf0c77f73.png)


This is then the expected behavior (whether we like it or not 😉).


💡 Bonus:
I personally recommend having Timon installed as a standalone app as well. This means I have two apps using the same PVA-bot. They are always in perfect sync. It also enables you to search for the bot's name in the search bar for example.

For a very long time, when I have both AdoptionHub and Timon as two different apps, the bot name (Timon) would still show as AdoptionHub like in your screenshot.

And here's the fun part. It looks like my setup now finally honors the original bot name! 
The profile picture is still associated with AdoptionHub though.

Standalone app for Timon:
![image](https://user-images.githubusercontent.com/65014935/163179393-1d179baf-605d-4a73-8d1a-ad15a2e236b3.png)

in AdoptionHub:
![image](https://user-images.githubusercontent.com/65014935/163179692-cb1f4c2a-e9ab-48cf-b769-b1f49af987ca.png)

**Comment by Erithano** [comment]
### 💡Bonus #2 @sharlotlek 

If you download Timon's [latest 2022 manifest ](https://github.com/Erithano/Timon-Your-FAQ-bot-for-Microsoft-Teams/blob/main/languages/english/Timon%20Empty%20Manifest%20EN%20-%202022%20update.zip)

You will get the new suggestions to play with.

BUT! Since you have AdoptionHub you would need to copy-paste the suggestions into the AdoptionHub Teams app (manifest) for it to show up there as well 🙂

Standalone user experience:
![image](https://user-images.githubusercontent.com/65014935/163182013-c981068a-4fc3-44a6-996d-df6ae07a4c0e.png)


AdoptionHub user experience:
![image](https://user-images.githubusercontent.com/65014935/163181861-e3701617-8029-4a85-bcf8-68e4a89182b2.png)



AdoptionHub manifest with suggestions added:
![image](https://user-images.githubusercontent.com/65014935/163181636-9532dbcf-f762-4890-9d2c-f2d8ef10ac65.png)


You can of course change the suggestions to whatever you want. 
If you do, just make sure your suggestions bring out the desired answer (maybe add a topic or trigger you want in PVA)

**Comment by sharlotlek** [comment]
@Erithano 

ohhh yeah !!! , Makes sense.🙂 

Thank you for the clarification. It would've been great for the bot to have its own name and icon within the app🙂
